palette = [
    ("header", "white,bold", "dark cyan"),
    ("footer", "white,bold", "dark cyan"),
    ("background", "white", "black"),
    ("group_listbox", "black", "brown"),
    ("group_item", "black", "yellow"),
    ("group_item_focus", "black", "dark blue"),
    ("group_item_shadow", "dark gray", "brown"),
    ("topic_item", "default", "default"),
    ("topic_item_focus", "standout", "default"),
    ("comment_item", "default", "default"),
    ("comment_item_focus", "standout", "default"),
    ("load_item", "default", "default"),
    ("load_item_focus", "standout", "default"),
]
